### PR TITLE
Fix problems

### PR DESCRIPTION
**Pull request by HenryTNH**
Fix 4.1.1 version and some layout problems

### CODE REVIEW

**Comment by StevenKo** [comment]
doctoractivity 要不要也加  viewPager.setOffscreenPageLimit(2);

**Comment by StevenKo** [comment]
screen shot 2016-02-23 at 5 06 14 pm
screen shot 2016-02-23 at 5 06 40 pm
還有兩個 view 也幫忙修一下，分別是 DivisionActivity 和 DoctorActivity

**Comment by StevenKo** [comment]
screen shot 2016-02-23 at 5 14 06 pm

**Comment by HenryTNH** [comment]
OK，上面的問題我一併修一下

**Comment by StevenKo** [comment]
HospitalDoctorActivity 的 77-81 行，幫我改成這樣，這樣業務邏輯才對！謝！        
       if (Build.VERSION.SDK_INT >= 23) {
            checkLocationPermission();
        } else {
            setGoogleClient();
        }

**Pull request closed without merging**
